import type { Product } from "@/types/product";

export const BEST_SELLERS: Product[] = [
    {
        id: "bs-001",
        slug: "burgundy-banarasi-silk",
        name: "Crimson Heritage Banarasi",
        fabric: "Pure Silk · Banarasi",
        actualPrice: 18500,
        discountedPrice: 13999,
        discountPercent: 24,
        image: "/products/saree-burgundy-banarasi.png",
        badge: "Bestseller",
        sku: "AD-BS-001",
        occasion: "Wedding",
        origin: "Varanasi, Uttar Pradesh",
        description:
            "A timeless masterpiece from the looms of Varanasi, this Banarasi silk saree in deep crimson is adorned with intricate golden zari weaving. The rich texture and lustrous sheen make it the perfect choice for grand occasions.",
        highlights: [
            "Handwoven by master weavers of Varanasi",
            "100% pure silk with real gold zari",
            "Rich pallu with temple motifs",
            "6 metres + 80 cm blouse piece included",
        ],
        careInstructions: [
            "Dry clean only",
            "Store wrapped in muslin cloth",
            "Avoid prolonged exposure to sunlight",
            "Do not wring or twist",
        ],
        availableColors: ["Crimson Red", "Royal Maroon", "Deep Wine"],
    },
    {
        id: "bs-002",
        slug: "royal-blue-kanjivaram",
        name: "Peacock Royal Kanjivaram",
        fabric: "Pure Silk · Kanjivaram",
        actualPrice: 22000,
        discountedPrice: 16499,
        discountPercent: 25,
        image: "/products/saree-blue-kanjivaram.png",
        badge: "Trending",
        sku: "AD-BS-002",
        occasion: "Wedding",
        origin: "Kanchipuram, Tamil Nadu",
        description:
            "Woven in the heart of Kanchipuram, this royal peacock-blue Kanjivaram saree showcases contrasting gold and magenta borders with rich temple motifs. Its heavy silk body and vibrant pallu are a testament to South India's weaving heritage.",
        highlights: [
            "Authentic Kanjivaram with GI tag certification",
            "Contrast magenta border with temple zari work",
            "High thread count for exceptional durability",
            "6 metres + 80 cm blouse piece included",
        ],
        careInstructions: [
            "Dry clean only",
            "Store in a cool, dry place",
            "Use a light starch to maintain body",
            "Air after each use before storing",
        ],
        availableColors: ["Peacock Blue", "Sapphire", "Teal"],
    },
    {
        id: "bs-003",
        slug: "blush-pink-chiffon",
        name: "Blossom Chiffon Elegance",
        fabric: "Pure Chiffon · Embroidered",
        actualPrice: 9800,
        discountedPrice: 7499,
        discountPercent: 23,
        image: "/products/saree-pink-chiffon.png",
        sku: "AD-BS-003",
        occasion: "Festive",
        origin: "Surat, Gujarat",
        description:
            "Light as a petal, this blush pink chiffon saree features delicate silver threadwork florals across its gossamer fabric. Perfect for festive evenings and celebrations, it drapes effortlessly for a graceful silhouette.",
        highlights: [
            "Ultra-lightweight pure chiffon base",
            "Silver thread floral embroidery throughout",
            "Fall and pico pre-stitched",
            "6 metres + 80 cm blouse piece included",
        ],
        careInstructions: [
            "Gentle hand wash in cold water",
            "Do not tumble dry",
            "Iron on low heat from reverse side",
            "Store flat to prevent creasing",
        ],
        availableColors: ["Blush Pink", "Ivory", "Lavender"],
    },
    {
        id: "bs-004",
        slug: "emerald-chanderi-silk",
        name: "Emerald Chanderi Grace",
        fabric: "Chanderi Silk · Handwoven",
        actualPrice: 12500,
        discountedPrice: 9299,
        discountPercent: 26,
        image: "/products/saree-green-chanderi.png",
        badge: "New",
        sku: "AD-BS-004",
        occasion: "Festive",
        origin: "Chanderi, Madhya Pradesh",
        description:
            "From the historic town of Chanderi comes this emerald green silk saree, woven with golden bootis and a lustrous silver border. Its characteristic transparency and lightness make it a versatile choice for festive and formal occasions alike.",
        highlights: [
            "Handwoven on traditional pit looms",
            "Delicate gold booti pattern throughout",
            "Silver zari border with peacock motifs",
            "6 metres + 80 cm blouse piece included",
        ],
        careInstructions: [
            "Dry clean recommended",
            "Hand wash gently if needed",
            "Store flat away from moisture",
            "Iron on low with a pressing cloth",
        ],
        availableColors: ["Emerald Green", "Forest Green", "Jade"],
    },
    {
        id: "bs-005",
        slug: "black-georgette-embroidery",
        name: "Midnight Zardozi Georgette",
        fabric: "Georgette · Zardozi Work",
        actualPrice: 24000,
        discountedPrice: 17999,
        discountPercent: 25,
        image: "/products/saree-black-georgette.png",
        badge: "Limited",
        sku: "AD-BS-005",
        occasion: "Wedding",
        origin: "Lucknow, Uttar Pradesh",
        description:
            "Draped in midnight black georgette, this saree features lavish zardozi embroidery with sequins and gold thread across the border and pallu. A statement piece for evening galas, receptions, and grand celebrations.",
        highlights: [
            "Heavy zardozi hand embroidery",
            "Gold sequin and cutdana embellishments",
            "Fully embroidered pallu",
            "6 metres + 80 cm blouse piece included",
        ],
        careInstructions: [
            "Dry clean only — embroidery is delicate",
            "Store spread flat, do not fold on embroidery",
            "Keep away from sharp objects",
            "Steam press only from reverse",
        ],
        availableColors: ["Midnight Black", "Deep Charcoal", "Onyx"],
    },
    {
        id: "bs-006",
        slug: "tussar-kalamkari",
        name: "Golden Kalamkari Tussar",
        fabric: "Tussar Silk · Hand-painted",
        actualPrice: 15000,
        discountedPrice: 11499,
        discountPercent: 23,
        image: "/products/saree-tussar-kalamkari.png",
        sku: "AD-BS-006",
        occasion: "Festive",
        origin: "Srikalahasti, Andhra Pradesh",
        description:
            "A celebration of India's ancient art, this tussar silk saree is hand-painted with kalamkari motifs — peacocks, lotuses, and folk patterns — using natural dyes. Each piece is a unique work of art that carries the artist's signature.",
        highlights: [
            "100% hand-painted with natural vegetable dyes",
            "Each piece is unique — no two are identical",
            "Traditional Srikalahasti Kalamkari style",
            "6 metres + 80 cm blouse piece included",
        ],
        careInstructions: [
            "Hand wash separately in cold water",
            "Mild detergent only — avoid bleach",
            "Dry in shade to preserve colour",
            "Iron on medium heat",
        ],
        availableColors: ["Golden Orange", "Rust Brown", "Ochre"],
    },
];

// ─── Helper: find a single product by slug ────────────────────────────────────
export function getProductBySlug(slug: string): Product | undefined {
    return BEST_SELLERS.find((p) => p.slug === slug);
}