// import type { Product } from "@/types/product";

// export const BEST_SELLERS: Product[] = [
//     {
//         id: "bs-001",
//         slug: "cotton-saree",
//         name: "Cotton Saree",
//         fabric: "Cotton · Lightweight",
//         actualPrice: 1427,
//         discountedPrice: 999,
//         discountPercent: 30,
//         image: "/products/saree-cotton.png",
//         sku: "AD-BS-001",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Elegant cotton saree featuring a soft texture and lightweight drape, perfect for daily wear, festive occasions, and casual elegance.",
//         highlights: [
//             "Soft, breathable pure cotton fabric",
//             "Lightweight drape for all-day comfort",
//             "Ideal for daily wear & festive occasions",
//             "6.30 metres including blouse piece",
//         ],
//         dimensions: { length: "6.30 meters including blouse piece", width: "45-47 inches" },
//         styleTip: "Pair it with minimal jewellery or oxidised accessories for a graceful look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store in a cool, dry place",
//             "Avoid prolonged exposure to sunlight",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-002",
//         slug: "bridal-benarasi-saree",
//         name: "Bridal Benarasi Saree",
//         fabric: "Silk · Benarasi Weave",
//         actualPrice: 4570,
//         discountedPrice: 3199,
//         discountPercent: 30,
//         image: "/products/saree-bridal-benarasi.png",
//         badge: "Bestseller",
//         sku: "AD-BS-002",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Luxurious bridal Benarasi saree featuring rich weaving, elegant texture, and timeless traditional craftsmanship perfect for weddings and grand occasions.",
//         highlights: [
//             "Rich Benarasi weaving with zari work",
//             "Timeless traditional craftsmanship",
//             "Luxurious texture perfect for weddings",
//             "6.30 metres including blouse piece",
//         ],
//         dimensions: { length: "6.30 meters including blouse piece", width: "45-47 inches" },
//         styleTip: "Pair it with traditional gold jewellery for a royal bridal look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store wrapped in muslin cloth",
//             "Avoid prolonged exposure to sunlight",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-003",
//         slug: "mirror-work-modal-silk-saree",
//         name: "Mirror Work Modal Silk Saree",
//         fabric: "Modal Silk · Mirror Work",
//         actualPrice: 3713,
//         discountedPrice: 2599,
//         discountPercent: 30,
//         image: "/products/saree-mirror-work-modal.png",
//         badge: "Trending",
//         sku: "AD-BS-003",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Elegant modal silk saree featuring premium mirror work detailing, soft luxurious texture, and graceful drape perfect for festive occasions, parties, and ethnic celebrations.",
//         highlights: [
//             "Premium mirror work embellishments",
//             "Soft, luxurious modal silk fabric",
//             "Graceful drape for festive occasions",
//             "6.30 metres including blouse piece",
//         ],
//         dimensions: { length: "6.30 meters including blouse piece", width: "45-47 inches" },
//         styleTip: "Pair it with oxidised or mirror jewellery for a stunning festive look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store in a cool, dry place",
//             "Avoid contact with sharp objects near mirror work",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-004",
//         slug: "tissue-kanjivaram-saree",
//         name: "Tissue Kanjivaram Saree",
//         fabric: "Tissue · Kanjivaram",
//         actualPrice: 3927,
//         discountedPrice: 2749,
//         discountPercent: 30,
//         image: "/products/saree-tissue-kanjivaram.png",
//         sku: "AD-BS-004",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Elegant tissue Kanjivaram saree featuring rich traditional weaving, luxurious shine, and graceful drape perfect for weddings, festive occasions, and ethnic celebrations.",
//         highlights: [
//             "Rich traditional Kanjivaram weaving",
//             "Luxurious tissue fabric with natural sheen",
//             "Graceful drape for weddings & celebrations",
//             "6.30 metres including blouse piece",
//         ],
//         dimensions: { length: "6.30 meters including blouse piece", width: "45-47 inches" },
//         styleTip: "Pair it with temple jewellery or traditional gold accessories for a royal ethnic look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store in a cool, dry place",
//             "Avoid prolonged exposure to sunlight",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-005",
//         slug: "ananya-special-designer-saree",
//         name: "Ananya Special Designer Saree",
//         fabric: "Designer · Premium",
//         actualPrice: 3427,
//         discountedPrice: 2399,
//         discountPercent: 30,
//         image: "/products/saree-ananya-special.png",
//         badge: "New",
//         sku: "AD-BS-005",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Premium designer saree featuring elegant detailing, modern ethnic styling, and graceful drape perfect for parties, festive occasions, and special celebrations.",
//         highlights: [
//             "Elegant designer detailing & modern ethnic style",
//             "Premium fabric with graceful drape",
//             "Perfect for parties & special celebrations",
//             "6.30 metres including blouse piece",
//         ],
//         dimensions: { length: "6.30 meters including blouse piece", width: "45-47 inches" },
//         styleTip: "Pair it with statement jewellery and heels for a classy designer look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store wrapped in muslin cloth",
//             "Avoid prolonged exposure to sunlight",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-006",
//         slug: "dhonekhali-cotton-saree",
//         name: "Dhonekhali Cotton Saree",
//         fabric: "Handloom Cotton · Bengal",
//         actualPrice: 2427,
//         discountedPrice: 1699,
//         discountPercent: 30,
//         image: "/products/saree-dhonekhali-cotton.png",
//         sku: "AD-BS-006",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Traditional Dhonekhali cotton saree featuring lightweight breathable fabric, classic Bengal handloom weaving, and elegant everyday comfort perfect for casual wear and cultural occasions.",
//         highlights: [
//             "Authentic Bengal handloom weaving",
//             "Lightweight & breathable cotton fabric",
//             "Ideal for casual wear & cultural occasions",
//             "5.5 metres",
//         ],
//         dimensions: { length: "5.5 meters", width: "45-47 inches" },
//         styleTip: "Pair it with silver jewellery or a simple cotton blouse for an authentic Bengali look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store in a cool, dry place",
//             "Avoid prolonged exposure to sunlight",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-007",
//         slug: "organza-saree",
//         name: "Organza Saree",
//         fabric: "Organza · Sheer",
//         actualPrice: 3927,
//         discountedPrice: 2749,
//         discountPercent: 30,
//         image: "/products/saree-organza.png",
//         sku: "AD-BS-007",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Elegant organza saree featuring lightweight sheer fabric, luxurious texture, and graceful drape perfect for parties, festive occasions, and modern ethnic styling.",
//         highlights: [
//             "Lightweight sheer organza fabric",
//             "Luxurious texture with graceful drape",
//             "Perfect for parties & festive styling",
//             "6.30 metres including blouse piece",
//         ],
//         dimensions: { length: "6.30 meters including blouse piece", width: "45-47 inches" },
//         styleTip: "Pair it with pearl or statement jewellery for a classy elegant look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store flat to prevent creasing",
//             "Iron on low heat from reverse side",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-008",
//         slug: "cartoon-print-cotton-saree",
//         name: "Cartoon Print Cotton Saree",
//         fabric: "Cotton · Artistic Print",
//         actualPrice: 1570,
//         discountedPrice: 1099,
//         discountPercent: 30,
//         image: "/products/saree-cartoon-print.png",
//         badge: "New",
//         sku: "AD-BS-008",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Trendy cartoon print cotton saree featuring playful artistic prints, lightweight fabric, and comfortable drape perfect for casual outings, daily wear, and unique fashion styling.",
//         highlights: [
//             "Playful artistic cartoon prints",
//             "Lightweight & comfortable cotton fabric",
//             "Great for casual outings & daily wear",
//             "5.5 metres",
//         ],
//         dimensions: { length: "5.5 meters", width: "45-47 inches" },
//         styleTip: "Pair it with quirky accessories and minimal makeup for a fun modern look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Wash separately to avoid colour transfer",
//             "Avoid prolonged exposure to sunlight",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-009",
//         slug: "ananya-touch-designer-saree",
//         name: "Ananya Touch Designer Saree",
//         fabric: "Designer · Luxury Fabric",
//         actualPrice: 6993,
//         discountedPrice: 4895,
//         discountPercent: 30,
//         image: "/products/saree-ananya-touch.png",
//         badge: "Limited",
//         sku: "AD-BS-009",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Premium designer saree featuring elegant craftsmanship, luxurious fabric texture, and graceful drape perfect for weddings, parties, and festive occasions.",
//         highlights: [
//             "Elegant designer craftsmanship",
//             "Luxurious fabric with premium texture",
//             "Graceful drape for weddings & parties",
//             "6.30 metres including blouse piece",
//         ],
//         dimensions: { length: "6.30 meters including blouse piece", width: "45-47 inches" },
//         styleTip: "Pair it with statement jewellery and heels for a sophisticated designer look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store wrapped in muslin cloth",
//             "Avoid prolonged exposure to sunlight",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
//     {
//         id: "bs-010",
//         slug: "ananya-finish-designer-saree",
//         name: "Ananya Finish Designer Saree",
//         fabric: "Designer · Premium Finish",
//         actualPrice: 7570,
//         discountedPrice: 5299,
//         discountPercent: 30,
//         image: "/products/saree-ananya-finish.png",
//         badge: "Bestseller",
//         sku: "AD-BS-010",
//         taxInfo: "Taxes included",
//         shippingInfo: "Shipping calculated at checkout",
//         deliveryTime: "3-7 business days",
//         availability: "In stock",
//         description:
//             "Luxury designer saree featuring premium finishing, elegant detailing, and graceful drape perfect for weddings, festive celebrations, and special occasions.",
//         highlights: [
//             "Premium designer finish with elegant detailing",
//             "Graceful drape perfect for weddings & festive occasions",
//             "Rich texture with lustrous sheen",
//             "6.30 metres including blouse piece",
//         ],
//         dimensions: { length: "6.30 meters including blouse piece", width: "45-47 inches" },
//         styleTip: "Pair it with premium accessories and traditional jewellery for a rich ethnic look.",
//         note: "Slight colour variations may occur due to photography lighting and screen settings.",
//         careTip: "Normal handwash recommended, dry wash preferred for longer fabric life.",
//         careInstructions: [
//             "Normal handwash recommended",
//             "Dry wash preferred for longer fabric life",
//             "Store wrapped in muslin cloth",
//             "Avoid prolonged exposure to sunlight",
//         ],
//         returnPolicy: "Easy replacement available for damaged or incorrect products.",
//     },
// ];

// // ─── Helper: find a single product by slug ────────────────────────────────────
// export function getProductBySlug(slug: string): Product | undefined {
//     return BEST_SELLERS.find((p) => p.slug === slug);
// }

